version: '2'
services:
    farmerconn-app:
        image: farmerconn
        external_links:
            - farmerconn-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/FarmerConn
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    farmerconn-postgresql:
        extends:
            file: postgresql.yml
            service: farmerconn-postgresql
